server:
  port: 8012

spring:
  application:
    name: product-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sevenhallo?currentSchema=demo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888/

#  cloud:
#    client:
#      hostname: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost2:8762/eureka
#  instance:
#    appname: product-service

management:
  endpoints:
    web:
      exposure:
        include=*:
